language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CI=TRAVISCI
script:
  - npm test
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
deploy:
  provider: pages
  name: Traian Stanciu
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master