export const FETCH_ROVERS_PENDING = "FETCH_ROVERS_PENDING";
export const FETCH_ROVERS_SUCCESS = "FETCH_ROVERS_SUCCESS";
export const FETCH_ROVERS_ERROR = "FETCH_ROVERS_ERROR";

export const SET_DATE_TYPE = "SET_DATE_TYPE";
export const SELECT_ROVER = "SELECT_ROVER";
export const SELECT_EARTH_DATE = "SELECT_EARTH_DATE";
export const SELECT_SOL_DATE = "SELECT_SOL_DATE";
export const SELECT_CAMERA = "SELECT_CAMERA";

export const FETCH_IMAGES_PENDING = "FETCH_IMAGES_PENDING";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_ERROR = "FETCH_IMAGES_ERROR";
